# Generated by Django 3.2.11 on 2022-01-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emojis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emojis',
            name='apple_version',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
