# Generated by Django 3.2.11 on 2022-01-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emojis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emojis',
            name='google_version',
        ),
        migrations.RemoveField(
            model_name='emojis',
            name='microsoft_version',
        ),
        migrations.RemoveField(
            model_name='emojis',
            name='samsung_version',
        ),
    ]
