# Generated by Django 3.2.11 on 2022-01-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emojis', '0002_auto_20220118_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='emojis',
            name='google_version',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
